# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76c685abf2ee88ff9d8c7ffb9a3f200d6debf94e7dae162e117f89c7b163980a65d8857e258d071f8a9ef274e0eead2630316a3c95db65c2b30dc6a86b238655

test:
  secret_key_base: 976ce4efe31b28b198815407f4ced9eee2413ec96b3f0f31c0a9dfc08808b9dae2ad0549aae51e562c10bcfcaf1dc43c194148bf601b1edbd25950e1f021eb55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
